flatpak_base:
  - com.github.tchx84.Flatseal

flatpak_extras:

  # Multimedia
  - com.spotify.Client
  - org.musicbrainz.Picard 

  # Editing
  - org.inkscape.Inkscape 
  - org.kde.krita
  - org.libreoffice.LibreOffice 
  - org.shotcut.Shotcut
  - org.tenacityaudio.Tenacity

  # Programming
  - cc.arduino.IDE2
  - com.github.corna.Vivado

  # Other
  - com.vivaldi.Vivaldi
  - org.qbittorrent.qBittorrent
  - org.signal.Signal
