cli_base_packages:
  - ansible
  - apt-file
  - atool
  - autoconf
  - bc
  - curl
  - default-jre
  - exfat-fuse
  - ffmpeg
  - fzf
  - gcc
  - git
  - grc
  - htop
  - libtool
  - lm-sensors
  - make
  - man
  - ncal
  - ntfs-3g
  - vim
  - network-manager
  - p7zip-full
  - pass
  - pipx
  - ssh
  - stow
  - sudo
  - tree
  - unzip
  - wget
  - xclip
  - zsh

cli_extras_packages:
  - cowsay
  - bsdgames
  - dict-gcide
  - dict-wn
  - dictd
  - fortune
  - gdb
  - gnuplot
  - neofetch
  - newsboat
  - npm
  - orpie
  - pandoc
  - python3-matplotlib
  - texlive-full
  - valgrind
  - vite

gui_base_packages:
  - alsa-utils
  - arandr
  - autorandr
  - feh
  - fonts-noto-color-emoji
  - hsetroot
  - i3lock
  - libsdl2-image-2.0-0 
  - libsdl2-mixer-2.0-0
  - libsdl2-ttf-2.0-0
  - libx11-dev
  - libx11-xcb-dev 
  - libxcb-res0-dev
  - libxcb-xkb-dev 
  - libxft-dev
  - libxinerama-dev
  - libxkbcommon-x11-dev 
  - libxrandr-dev
  - libxtst-dev
  - numlockx
  - pavucontrol
  - picom
  - pulseaudio
  - pulseaudio-module-bluetooth
  - pulsemixer
  - rofi
  - scrot
  - unifont
  - x11-utils
  - x11-xkb-utils 
  - x11-xserver-utils
  - xcb 
  - xcompmgr
  - xfonts-terminus
  - xinit
  - xinput
  - xserver-xorg-core
  - xserver-xorg-input-libinput
  - xss-lock
  - xutils-dev

gui_extras_packages:
  - cups
  - mpv
  - mpd
  - ncmpcpp
  - wine
  - zathura
