cli_base_stow:
  - bash
  - grc
  - htop
  - nvim
  - scripts
  - tmux
  - top
  - zsh

cli_extras_stow:
  - newsboat
  - mpd

gui_base_stow:
  - autorandr
  - fonts
  - picom
  - rofi
  - wallpapers
  - x-windows
