cli_base_stow:
  - bash
  - fsh
  - grc
  - htop
  - nvim
  - scripts
  - tmux
  - top
  - zsh

cli_extras_stow:
  # - newsboat
  # - mpd
  - npm

gui_base_stow:
  - autorandr
  - dunst
  - fonts
  - picom
  - rofi
  - wallpapers
  - xorg

gui_extras_stow:
  - zathura
