- name: Install cli extras
  become: true
  apt:
    name: "{{ cli_extras_packages }}"
    state: present
    update_cache: true
  tags:
    - extras

- name: Stow cli extras
  shell: "stow -d {{ playbook_dir }}/../config -t ~/ -v --adopt {{ item }}"
  loop: "{{ cli_extras_stow }}"
  tags:
    - extras
