- name: Install cli base
  become: yes
  apt:
    name: "{{ cli_base_packages }}"
    state: present
    update_cache: yes
  tags:
    - base

- name: Stow cli base
  shell: "stow -d {{ playbook_dir }}/../config -t ~/ -v --adopt {{ item }}"
  loop: "{{ cli_base_stow }}"
  tags:
    - base

- name: Set zsh as default shell
  become: true
  shell: "chsh -s /bin/zsh"
  tags:
    - base
