- name: Create .fonts symlink
  file:
    src: "{{ playbook_dir }}/../files/.fonts"
    dest: "~/.fonts"
    force: true
    state: link
  tags:
    - gui
    - fonts

- name: Rebuild font cache
  shell: "fc-cache -f -v"
  tags:
    - gui
    - fonts
