- name: Install gui base
  become: yes
  apt:
    name: "{{ gui_base_packages }}"
    state: present
    update_cache: yes
  tags:
    - gui

- name: Stow gui base
  shell: "stow -d {{ playbook_dir }}/../config -t ~/ -v {{ item }}"
  loop: "{{ gui_base_stow }}"
  tags:
    - gui
    - config
