- name: Install gui base
  become: yes
  apt:
    name: "{{ gui_base_packages }}"
    state: present
    update_cache: yes
  tags:
    - gui

- name: Stow gui base
  shell: "stow -d {{ playbook_dir }}/../config -t ~/ -v {{ item }}"
  loop: "{{ gui_base_stow }}"
  tags:
    - gui

- name: Build dwm
  make:
    chdir: "{{ playbook_dir }}/../source/dwm"
    target: install
    become: yes
  tags:
    - gui
    - suckless

- name: Build st
  make:
    chdir: "{{ playbook_dir }}/../source/st"
    target: install
    become: yes
  tags:
    - gui
    - suckless

- name: Build dwmblocks
  make:
    chdir: "{{ playbook_dir }}/../source/dwmblocks"
    target: install
    become: yes
  tags:
    - gui
    - suckless

- name: Rebuild font cache
  shell: "fc-cache -f -v"
  tags:
    - gui
