- name: Install gui base
  become: yes
  apt:
    name: "{{ gui_base_packages }}"
    state: present
    update_cache: yes
  tags:
    - gui

- name: Stow gui base
  shell: "stow -d {{ playbook_dir }}/../config -t ~/ -v {{ item }}"
  loop: "{{ gui_base_stow }}"
  tags:
    - gui
    - config

- name: Create .fonts symlink
  file:
    src: "{{ playbook_dir }}/../files/.fonts"
    dest: "~/.fonts"
    force: true
    state: link
  tags:
    - gui
    - config
    - fonts

- name: Rebuild font cache
  shell: "fc-cache -f -v"
  tags:
    - gui
    - confi
    - fonts
