- name: Hayden's automated Debian setup script
  hosts: localhost

  pre_tasks:

    - name: Unstow programs
      #shell: "for NAME in {{ playbook_dir }}/../config/*; do stow -d {{ playbook_dir }}/../config -t ~/ -D ${NAME#../config/}; done"
      shell: "for NAME in {{ playbook_dir }}/../config/*; do echo ${NAME#../config/}; done"
      ignore_errors: false

    - name: Copy repo template
      vars:
        apt_components: main contrib non-free non-free-firmware
      become: true
      copy:
        dest: /etc/apt/sources.list
        mode: 0644
        owner: root
        group: root
        content: |
          deb http://deb.debian.org/debian/ {{ ansible_distribution_release }} {{ apt_components }}
          deb-src http://deb.debian.org/debian/ {{ ansible_distribution_release }} {{ apt_components }}

          deb http://security.debian.org/debian-security {{ ansible_distribution_release }}-security {{ apt_components }}
          deb-src http://security.debian.org/debian-security {{ ansible_distribution_release }}-security {{ apt_components }}

          deb http://deb.debian.org/debian/ {{ ansible_distribution_release }}-updates {{ apt_components }}
          deb-src http://deb.debian.org/debian/ {{ ansible_distribution_release }}-updates {{ apt_components }}

    - name: Upgrade package list
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present

    - name: Install prerequisite packages
      become: yes
      apt:
        name:
          - stow
          - wget
          - git
        update_cache: true
        state: present

    - name: Make home directories
      file:
        path: "{{ lookup('env', 'HOME') }}/{{ item }}"
        state: directory
        mode: 0755
      loop:
        - "Documents"
        - "Downloads"
        - "Git"
        - "Music"
        - "Photos"
        - "Photos/screenshots"
        - "School"
        - "School/archive"

    - name: Include variables
      include_vars: "{{ item }}"
      loop: "{{ query('fileglob', 'vars/*.yml') }}"

  tasks:
    - include: tasks/cli-base.yml
    - include: tasks/cli-extras.yml
    - include: tasks/gui-base.yml
    - include: tasks/gui-extras.yml
    - include: tasks/bluetooth.yml
    - include: tasks/flatpak.yml
    - include: tasks/kjv.yml
