vsync = true;
backend = "glx";
corner-radius = 10;
rounded-corners-exclude = [ "class_g     = 'dwm'" ];
shadow = true;
fading = true;
fade-in-step = 0.08;
fade-out-step = 0.08;

blur-background = true;
blur:
{
    method = "gaussian";
    size = 3; 
    deviation = 15;
};

