vsync = true;
backend = "glx";
corner-radius = 15;
rounded-corners-exclude = [ "class_g     = 'dwm'" ];
shadow = true;
fading = true;
fade-in-step = 0.08;
fade-out-step = 0.08;

blur-background = true;
blur:
{
    method = "dual_kawase";
    strength = 1;
};

rules: (
# 1. Your borderless window rule
        {
        match = "border_width = 0";
        corner-radius = 0;
        },
# 2. Convert rounded-corners-exclude
        {
        match = "class_g = 'dwm'";
        corner-radius = 0;
        },
# 3. Convert xcorners excludes (blur, shadow, and fade)
        {
        match = "class_g = 'xcorners'";
        blur-background = false;
        shadow = false;
        fade = false;
        },
        {
        match = "class_g = 'Dunst'";
        shadow = false;
        },
{
    match = "class_g = 'Rofi'";
    shadow = false;
},
{
    match = "class_g = 'vivaldi'";
    shadow = false;
},
{
    match = "window_type = 'menu' || window_type = 'dropdown_menu' || window_type = 'popup_menu'";
    shadow = false;
    blur-background = false;
}
);
